#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# Basic Ubuntu setup
cookbook 'locale',            '~> 1.0.2'
cookbook 'apt-upgrade-once',  '~> 0.1.0'
cookbook 'apt',               '~> 2.6.1'
cookbook 'build-essential',   '~> 2.1.3'

# For all RideConnection nodes
cookbook 'logrotate',         '~> 1.8.0'
cookbook 'apticron',          '~> 0.2.0'

# For DB nodes
cookbook 'postgresql',        '~> 3.4.14'
cookbook 'postgis',           '~> 0.3.0'
cookbook 'database',          '~> 4.0.3'

# For Web nodes
cookbook 'apache2',           '~> 1.0' # v1.0 satisfies passenger_apache2 dependency
cookbook 'passenger_apache2', '~> 2.2.3'
cookbook 'imagemagick',       '~> 0.2.3'
cookbook 'git',               '~> 4.1.0'
cookbook 'rvm',               '~> 0.9.2'
