#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# Basic Ubuntu setup
cookbook 'apt',              '~> 2.6.1'
cookbook 'apt-upgrade-once', '~> 0.1.0'
cookbook 'build-essential',  '~> 2.1.3'
cookbook 'locale',           '~> 1.0.2'
cookbook 'timezone-ii',      '~> 0.2.0'

# For all RideConnection nodes
cookbook 'apticron',         '~> 0.2.0'
cookbook 'logrotate',        '~> 1.8.0'

# For DB nodes
cookbook 'database',         '~> 4.0.3'
cookbook 'postgis',          '~> 0.3.0'
cookbook 'postgresql',       '~> 3.4.14'

# For Web nodes
cookbook 'apache2',          '~> 3.0.1'
cookbook 'git',              '~> 4.1.0'
cookbook 'imagemagick',      '~> 0.2.3'
cookbook 'rvm',              :git => 'https://github.com/fnichol/chef-rvm', :ref => "7e1d452eeda083c1048ea94d513b58df78ad5350" # '~> 0.9.3'
cookbook 'rvm_passenger',    :git => 'https://github.com/chrisbloom7/chef-rvm_passenger'
cookbook 'swap',             '~> 0.3.8'
